name: workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Readme.md'
jobs:
  integration:
    name: continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting Repository"

      - name: Run unit tests
        run: echo "Running Unit Tests"